name: Run QA Automation

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  runAutomation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Run Automation Tests
        run: ./run-tests.sh  # or the command to start your automation framework
